use super::strings;
use agent_os_sys::*;

pub(super) fn core_permissions(now: &str) -> Vec<PermissionProfile> {
    vec![
        PermissionProfile {
            permission_profile_id: "perm_supervisor".to_string(),
            status: ProfileStatus::Active,
            name: "SupervisorPermission".to_string(),
            max_risk_level: 6,
            allowed_syscalls: strings(&["*"]),
            resource_scopes: strings(&["*"]),
            denied_tool_classes: Vec::new(),
            approval_required_above: 5,
            requires_evidence_for: strings(&["final.submit"]),
            created_at: now.to_string(),
            updated_at: now.to_string(),
            superseded_by: None,
        },
        PermissionProfile {
            permission_profile_id: "perm_worker".to_string(),
            status: ProfileStatus::Active,
            name: "WorkerPermission".to_string(),
            max_risk_level: 4,
            allowed_syscalls: strings(&[
                "context.load",
                "artifact.commit",
                "evidence.attach",
                "task.update",
                "task.block",
                "task.complete",
                "tool.discover",
                "tool.invoke",
                "comm.send_supervisor",
                "blackboard.post",
                "memento.create",
                "memento.arm",
                "memento.consume",
                "review.request",
                "verify.request",
                "agent.yield",
                "agent.complete",
                "agent.fail",
            ]),
            resource_scopes: strings(&[
                "read:*",
                "test:*",
                "workspace:*",
                "artifact:*",
                "evidence:*",
                "task:*",
                "tool:*",
                "comm:*",
                "blackboard:*",
                "memento:*",
                "review:*",
                "verify:*",
                "agent:*",
            ]),
            denied_tool_classes: Vec::new(),
            approval_required_above: 4,
            requires_evidence_for: strings(&["artifact.commit:patch", "artifact.commit:test_log"]),
            created_at: now.to_string(),
            updated_at: now.to_string(),
            superseded_by: None,
        },
        PermissionProfile {
            permission_profile_id: "perm_reviewer".to_string(),
            status: ProfileStatus::Active,
            name: "ReviewerPermission".to_string(),
            max_risk_level: 1,
            allowed_syscalls: strings(&[
                "context.load",
                "review.submit",
                "evidence.attach",
                "tool.discover",
                "comm.send_supervisor",
                "blackboard.post",
                "agent.yield",
                "agent.complete",
                "agent.fail",
            ]),
            resource_scopes: strings(&[
                "read:*",
                "review:*",
                "evidence:*",
                "tool:*",
                "comm:*",
                "blackboard:*",
                "agent:*",
            ]),
            denied_tool_classes: strings(&["filesystem.write"]),
            approval_required_above: 1,
            requires_evidence_for: strings(&["review.submit"]),
            created_at: now.to_string(),
            updated_at: now.to_string(),
            superseded_by: None,
        },
    ]
}
