use super::strings;
use agent_os_sys::*;

pub(super) fn core_permissions(now: &str) -> Vec<PermissionProfile> {
    vec![
        PermissionProfile {
            permission_profile_id: "perm_supervisor".to_string(),
            status: ProfileStatus::Active,
            name: "SupervisorPermission".to_string(),
            permission_set: PermissionSet {
                max_risk_level: 6,
                allowed_syscalls: strings(&["*"]),
                resource_scopes: strings(&["*"]),
                allowed_tool_names: strings(&["*"]),
                allowed_tool_driver_classes: all_tool_driver_classes(),
                approval_required_above: 5,
                requires_evidence_for: strings(&["final.submit"]),
            },
            created_at: now.to_string(),
            updated_at: now.to_string(),
            superseded_by: None,
        },
        PermissionProfile {
            permission_profile_id: "perm_worker".to_string(),
            status: ProfileStatus::Active,
            name: "WorkerPermission".to_string(),
            permission_set: PermissionSet {
                max_risk_level: 4,
                allowed_syscalls: strings(&[
                    "context.load",
                    "context.invalidate",
                    "context.commit_summary",
                    "memory.propose_write",
                    "memory.commit_write",
                    "memory.invalidate",
                    "artifact.commit",
                    "evidence.attach",
                    "task.update",
                    "task.block",
                    "task.complete",
                    "tool.discover",
                    "tool.invoke",
                    "comm.send_supervisor",
                    "blackboard.post",
                    "memento.create",
                    "memento.arm",
                    "memento.consume",
                    "review.request",
                    "verify.request",
                    "agent.yield",
                    "agent.complete",
                    "agent.fail",
                ]),
                resource_scopes: strings(&[
                    "read:*",
                    "context:*",
                    "memory:*",
                    "test:*",
                    "workspace:*",
                    "artifact:*",
                    "evidence:*",
                    "task:*",
                    "tool:*",
                    "instruction:*",
                    "skill:*",
                    "skill_file:*",
                    "mcp:*",
                    "comm:*",
                    "blackboard:*",
                    "memento:*",
                    "review:*",
                    "verify:*",
                    "agent:*",
                ]),
                allowed_tool_names: strings(&[
                    "apply_patch",
                    "read_file",
                    "run_command",
                    "accomplish_goal",
                    "update_checklist",
                    "record_evidence",
                    "report_supervisor",
                    "post_blackboard",
                    "request_permissions",
                    "load_skill",
                    "read_skill_resource",
                    "submit_final",
                ]),
                allowed_tool_driver_classes: strings_tool_driver_classes(&[
                    ToolDriverClass::Filesystem,
                    ToolDriverClass::Shell,
                    ToolDriverClass::KernelBuiltin,
                    ToolDriverClass::Mcp,
                ]),
                approval_required_above: 4,
                requires_evidence_for: strings(&[
                    "artifact.commit:patch",
                    "artifact.commit:test_log",
                ]),
            },
            created_at: now.to_string(),
            updated_at: now.to_string(),
            superseded_by: None,
        },
        PermissionProfile {
            permission_profile_id: "perm_reviewer".to_string(),
            status: ProfileStatus::Active,
            name: "ReviewerPermission".to_string(),
            permission_set: PermissionSet {
                max_risk_level: 1,
                allowed_syscalls: strings(&[
                    "context.load",
                    "review.submit",
                    "evidence.attach",
                    "tool.discover",
                    "comm.send_supervisor",
                    "blackboard.post",
                    "agent.yield",
                    "agent.complete",
                    "agent.fail",
                    "tool.invoke",
                ]),
                resource_scopes: strings(&[
                    "read:*",
                    "review:*",
                    "evidence:*",
                    "tool:*",
                    "comm:*",
                    "blackboard:*",
                    "agent:*",
                ]),
                allowed_tool_names: strings(&[
                    "read_file",
                    "record_evidence",
                    "report_supervisor",
                    "post_blackboard",
                    "request_permissions",
                    "submit_final",
                ]),
                allowed_tool_driver_classes: strings_tool_driver_classes(&[
                    ToolDriverClass::Filesystem,
                    ToolDriverClass::KernelBuiltin,
                ]),
                approval_required_above: 1,
                requires_evidence_for: strings(&["review.submit"]),
            },
            created_at: now.to_string(),
            updated_at: now.to_string(),
            superseded_by: None,
        },
    ]
}

fn all_tool_driver_classes() -> Vec<ToolDriverClass> {
    vec![
        ToolDriverClass::KernelBuiltin,
        ToolDriverClass::Filesystem,
        ToolDriverClass::Shell,
        ToolDriverClass::Git,
        ToolDriverClass::Mcp,
        ToolDriverClass::Browser,
        ToolDriverClass::ExternalApi,
    ]
}

fn strings_tool_driver_classes(classes: &[ToolDriverClass]) -> Vec<ToolDriverClass> {
    classes.to_vec()
}
